# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20160827_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
